# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4458c735b1885a9b4d26d77a7f04ce9a01c3d794e3238748f0a791c0946ad5b84eb5640dcf2ff0f67256cbed4cf9d517a81a376a12ef77559c8dca2a76a886d7

test:
  secret_key_base: 27c3e86a8c3d5d0a12e5c69aa97dfcd216aa93448da4bda8c400dfb85e9269e3292c2010fb38222b6f620e98dee0a725556e4e0ace168f4c8ec84707fe5927d6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
